### PR TITLE
Fix for Julia v1.11

### LINKED ISSUE #37: Test fails on 1.11
See https://github.com/JuliaLang/julia/issues/53591 for details.

### PR DESCRIPTION
**Pull request by mbauman**
Fixes #37

### CODE REVIEW

File: src/InvertedIndices.jl [hunk 1]
```diff
@@ -183,12 +183,15 @@ end
...
 # This is an interesting need — we need this because otherwise indexing with a
 # single multidimensional boolean array ends up comparing a multidimensional cartesian
-# index to a linear index. Does this need addressing in Base, too?
+# index to a linear index.
 @inline Base.to_indices(A, I::Tuple{Not{<:NIdx{1}}}) = to_indices(A, (eachindex(IndexLinear(), A),), I)
 @inline Base.to_indices(A, I::Tuple{Not{<:NIdx}}) = to_indices(A, axes(A), I)
-# Arrays of Bool are even more confusing as they're sometimes linear and sometimes not
-@inline Base.to_indices(A, I::Tuple{Not{<:AbstractArray{Bool, 1}}}) = to_indices(A, (eachindex(IndexLinear(), A),), I)
-@inline Base.to_indices(A, I::Tuple{Not{<:Union{Array{Bool}, BitArray}}}) = to_indices(A, (eachindex(A),), I)
+if VERSION < v"1.11"
```
Comment (ararslan) [inline src/InvertedIndices.jl]:
```suggestion
if VERSION < v"1.11.0-DEV.1157"
```
This is the `contrib/commit-name.sh` output for the PR noted in the comment.

**Review by ararslan — APPROVED** [review]
