### PR TITLE
fix performance

### LINKED ISSUE #14: Significant performance cost over naively filtering indices
I went to port [Jackknife](https://github.com/ararslan/Jackknife.jl) over to use InvertedIndices, but I noticed something... suboptimal.

Below are some timings for using InvertedIndices (`thing1`) and using the current naive approach for skipping indices (`thing2`).
```
julia> using InvertedIndices, Statistics, BenchmarkTools

julia> thing1(f, x) = map(i->f(view(x, Not(i))), eachindex(x))
thing1 (generic function with 1 method)

julia> thing2(f, x) = (is = eachindex(x); map(i->f(view(x, filter(!isequal(i), is))), is))
thing2 (generic function with 1 method)

julia> x = randn(2000);

julia> @benchmark thing1(mean, $x)
BenchmarkTools.Trial:
  memory estimate:  792.91 MiB
  allocs estimate:  27954027
  --------------
  minimum time:     2.523 s (1.98% GC)
  median time:      2.564 s (2.81% GC)
  mean time:        2.564 s (2.81% GC)
  maximum time:     2.605 s (3.61% GC)
  --------------
  samples:          2
  evals/sample:     1

julia> @benchmark thing2(mean, $x)
BenchmarkTools.Trial:
  memory estimate:  35.48 MiB
  allocs estimate:  28005
  --------------
  minimum time:     18.324 ms (3.89% GC)
  median time:      20.482 ms (10.97% GC)
  mean time:        20.770 ms (11.10% GC)
  maximum time:     64.851 ms (64.83% GC)
  --------------
  samples:          241
  evals/sample:     1
```
That's pretty hardcore. Am I doing something wrong in how I'm using it here?

### LINKED ISSUE #27: Bad performance caused by type unstable `iterate`
I tried to compare the performance of indexing :
```julia
function benchindexing(a, not)
    print("indexing by `!in(not)`:     ")
    @btime $a[map(!in($not), axes($a, 1))]
    print("indexing by `!in(Set(not))`:")
    @btime $a[map(!in(Set($not)), axes($a, 1))]
    print("indexing by `Not(not)`:     ")
    @btime $a[Not($not)]
    return nothing
end
```

For most of case, `Not(not)` is much slower than `map(!in(not), axes(a, 1))`:
```julia
julia> benchindexing(rand(100), 1)
indexing by `!in(not)`:        224.546 ns (2 allocations: 1.06 KiB)
indexing by `!in(Set(not))`:   679.196 ns (6 allocations: 1.53 KiB)
indexing by `Not(not)`:        13.666 μs (497 allocations: 16.34 KiB)

julia> benchindexing(rand(100), 1:10)
indexing by `!in(not)`:        229.121 ns (2 allocations: 1008 bytes)
indexing by `!in(Set(not))`:   722.948 ns (6 allocations: 1.45 KiB)
indexing by `Not(not)`:        12.292 μs (452 allocations: 14.89 KiB)

julia> benchindexing(rand(100), collect(1:10))
indexing by `!in(not)`:        598.545 ns (2 allocations: 1008 bytes)
indexing by `!in(Set(not))`:   712.652 ns (6 allocations: 1.45 KiB)
indexing by `Not(not)`:        12.500 μs (452 allocations: 14.89 KiB)

julia> benchindexing(rand(100), collect(1:50))
indexing by `!in(not)`:        1.483 μs (2 allocations: 688 bytes)
indexing by `!in(Set(not))`:   1.087 μs (9 allocations: 2.35 KiB)
indexing by `Not(not)`:        7.083 μs (252 allocations: 8.33 KiB)

julia> benchindexing(rand(100), collect(1:100))
indexing by `!in(not)`:        2.176 μs (2 allocations: 272 bytes)
indexing by `!in(Set(not))`:   1.454 μs (9 allocations: 3.07 KiB)
indexing by `Not(not)`:        285.223 ns (5 allocations: 224 bytes)

julia> benchindexing(rand(10000), collect(1:5000))
indexing by `!in(not)`:        11.821 ms (3 allocations: 49.08 KiB)
indexing by `!in(Set(not))`:   200.125 μs (10 allocations: 121.74 KiB)
indexing by `Not(not)`:        735.792 μs (35003 allocations: 976.67 KiB)

julia> benchindexing(rand(10000), collect(1:8000))
indexing by `!in(not)`:        15.105 ms (2 allocations: 25.69 KiB)
indexing by `!in(Set(not))`:   181.125 μs (9 allocations: 170.35 KiB)
indexing by `Not(not)`:        309.500 μs (14002 allocations: 390.78 KiB)

julia> benchindexing(rand(10000), collect(1:10000))
indexing by `!in(not)`:        15.769 ms (2 allocations: 10.02 KiB)
indexing by `!in(Set(not))`:   218.042 μs (9 allocations: 154.68 KiB)
indexing by `Not(not)`:        16.250 μs (5 allocations: 224 bytes)
```

There are a much more allocations, which are caused by `collect(::Base.Generator{InvertedIndices.InvertedIndexIterator{...})`:
```julia
julia> @btime collect(itr) setup=(itr=(i for i in to_indices(rand(100), (Not(1:50),))[1]));
  6.990 μs (253 allocations: 8.36 KiB)
```

The `code_warntype` shows:
```julia
julia> code_warntype(collect, (Base.Generator{InvertedIndices.InvertedIndexIterator{Int64, UnitRange{Int64}, Base.OneTo{Int64}}, typeof(identity)},))
Variables
  #self#::Core.Const(collect)
  itr::Base.Generator{InvertedIndices.InvertedIndexIterator{Int64, UnitRange{Int64}, Base.OneTo{Int64}}, typeof(identity)}
  @_3::Int64
  arr::Vector{Int64}
  st::Tuple{Union{Nothing, Tuple{Int64, Int64}}, Union{Nothing, Tuple{Int64, Int64}}}
  v1::Int64
  y::Union{Nothing, Tuple{Int64, Tuple{Union{Nothing, Tuple{Int64, Int64}}, Union{Nothing, Tuple{Int64, Int64}}}}}
  shape::Tuple{Base.OneTo{Int64}}
  et::Type{Int64}
  isz::Base.HasShape{1}
  @_11::Type{Int64}
  @_12::Tuple{Base.OneTo{Int64}}

...
```
where `y = iterate(itr)` and `st = y[2]` are type unstable.

IMO, the type instability of `iterate(::InvertedIndexIterator)` causes the bad performance. Is there any way to fix it?

Besides, I suggest that for `Not{S}` where `S<:Integer` or `S <: AbstractRange`, `to_indices` should convert it to a `Base.LogicalIndex` by `Base.LogicalIndex(map(!in(not), ind)`, because its is really faster:
```Julia
julia> benchindexing(rand(10000), 1:10000)
indexing by `!in(not)`:        5.972 μs (2 allocations: 10.02 KiB)
indexing by `!in(Set(not))`:   215.750 μs (9 allocations: 154.68 KiB)
indexing by `Not(not)`:        14.625 μs (5 allocations: 224 bytes)

julia> benchindexing(rand(10000), 1:2:10000)
indexing by `!in(not)`:        69.958 μs (3 allocations: 49.08 KiB)
indexing by `!in(Set(not))`:   200.250 μs (10 allocations: 121.74 KiB)
indexing by `Not(not)`:        794.416 μs (39492 allocations: 1.40 MiB)
```

### PR DESCRIPTION
**Pull request by mbauman**
Previously, we had been plopping the return values of both `iterate(I.skips)` and `iterate(I.picks)` in a single tuple to use as the iteration state.  This meant that we had a type instability of the flavor:

```julia
(skipitr, pickitr)::Tuple{Union{Nothing, Tuple{_, _}}, Union{Nothing, Tuple{_, _}}
```

Julia's inference _does not like this_.  In particular, this isn't a small splittable union.  This change refactors iteration with two dramatic simplifications:

1. We no longer carry around the previously returned index from the `pickitr`.  Changing this to only worry about the _state_ from the picks gets rid of one union split and simplifies things such that the iteration of picks is lock-step with the iteration itself; we're no longer one ahead.
2. We do still need to carry around the previously returned skipper — it's the _next_ value we need to skip!  But here we can introduce a branch to either return a `(nothing, pickstate)` or a `((skipvalue, skipstate), pickstate)`, which is exactly the magic we need to get Julia to normalize the `Tuple{Union}` to a `Union{Tuple, Tuple}`.

fixes #14, fixes #27

### CODE REVIEW

**Comment by mbauman** [comment]
Using the benchmark suite from #27, this is now far and away the fastest of all but one of the cases by 5-50x.  The odd one out is `rand(10000)[Not(1:10000)]` — the second to last test here:

```
julia> using BenchmarkTools, InvertedIndices
Precompiling InvertedIndices
  1 dependency successfully precompiled in 1 seconds

julia> function benchindexing(a, not)
           print("indexing by `!in(not)`:     ")
           @btime $a[map(!in($not), axes($a, 1))]
           print("indexing by `!in(Set(not))`:")
           @btime $a[map(!in(Set($not)), axes($a, 1))]
           print("indexing by `Not(not)`:     ")
           @btime $a[Not($not)]
           return nothing
       end
benchindexing (generic function with 1 method)

julia> benchindexing(rand(100), 1)
indexing by `!in(not)`:       144.704 ns (2 allocations: 1.03 KiB)
indexing by `!in(Set(not))`:  504.510 ns (6 allocations: 1.42 KiB)
indexing by `Not(not)`:       76.090 ns (1 allocation: 896 bytes)

julia> benchindexing(rand(100), 1:10)
indexing by `!in(not)`:       137.191 ns (2 allocations: 976 bytes)
indexing by `!in(Set(not))`:  521.597 ns (6 allocations: 1.34 KiB)
indexing by `Not(not)`:       84.454 ns (1 allocation: 816 bytes)

julia> benchindexing(rand(100), collect(1:10))
indexing by `!in(not)`:       530.263 ns (2 allocations: 976 bytes)
indexing by `!in(Set(not))`:  528.947 ns (6 allocations: 1.34 KiB)
indexing by `Not(not)`:       90.097 ns (1 allocation: 816 bytes)

julia> benchindexing(rand(100), collect(1:50))
indexing by `!in(not)`:       1.442 μs (2 allocations: 656 bytes)
indexing by `!in(Set(not))`:  829.392 ns (9 allocations: 2.24 KiB)
indexing by `Not(not)`:       99.657 ns (1 allocation: 496 bytes)

julia> benchindexing(rand(100), collect(1:100))
indexing by `!in(not)`:       2.167 μs (2 allocations: 224 bytes)
indexing by `!in(Set(not))`:  1.125 μs (9 allocations: 3.01 KiB)
indexing by `Not(not)`:       126.206 ns (1 allocation: 64 bytes)

julia> benchindexing(rand(10000), collect(1:5000))
indexing by `!in(not)`:       11.734 ms (3 allocations: 49.17 KiB)
indexing by `!in(Set(not))`:  169.917 μs (10 allocations: 121.82 KiB)
indexing by `Not(not)`:       8.472 μs (2 allocations: 39.17 KiB)

julia> benchindexing(rand(10000), collect(1:8000))
indexing by `!in(not)`:       14.982 ms (2 allocations: 25.88 KiB)
indexing by `!in(Set(not))`:  154.333 μs (9 allocations: 170.52 KiB)
indexing by `Not(not)`:       8.820 μs (1 allocation: 15.88 KiB)

julia> benchindexing(rand(10000), collect(1:10000))
indexing by `!in(not)`:       15.615 ms (2 allocations: 10.06 KiB)
indexing by `!in(Set(not))`:  194.083 μs (9 allocations: 154.71 KiB)
indexing by `Not(not)`:       8.958 μs (1 allocation: 64 bytes)

julia> @btime collect(itr) setup=(itr=(i for i in to_indices(rand(100), (Not(1:50),))[1]));
  58.038 ns (1 allocation: 496 bytes)

julia> benchindexing(rand(10000), 1:10000)
indexing by `!in(not)`:       2.287 μs (2 allocations: 10.06 KiB)
indexing by `!in(Set(not))`:  182.000 μs (9 allocations: 154.71 KiB)
indexing by `Not(not)`:       6.217 μs (1 allocation: 64 bytes)

julia> benchindexing(rand(10000), 1:2:10000)
indexing by `!in(not)`:       31.792 μs (3 allocations: 49.17 KiB)
indexing by `!in(Set(not))`:  163.916 μs (10 allocations: 121.82 KiB)
indexing by `Not(not)`:       6.275 μs (2 allocations: 39.17 KiB)
```

**Comment by mbauman** [comment]
This fixes iterate, but interestingly it's still one step too complicated for `collect`, which is why #14 is still an order of magnitude away here:

```Julia
julia> using InvertedIndices, Statistics, BenchmarkTools

julia> thing1(f, x) = map(i->f(view(x, Not(i))), eachindex(x))
thing1 (generic function with 1 method)

julia> thing2(f, x) = (is = eachindex(x); map(i->f(view(x, filter(!isequal(i), is))), is))
thing2 (generic function with 1 method)

julia> x = randn(2000);

julia> @btime thing1(mean, $x);
  277.239 ms (14971031 allocations: 411.97 MiB)

julia> @btime thing2(mean, $x);
  9.928 ms (4001 allocations: 62.03 MiB)
```

all its time is being spent in collect, because:

```
julia> @code_warntype collect(I)
MethodInstance for collect(::InvertedIndices.InvertedIndexIterator{Int64, Int64, Base.OneTo{Int64}})
  from collect(III::InvertedIndices.InvertedIndexIterator) @ InvertedIndices ~/Projects/InvertedIndices.jl/src/InvertedIndices.jl:138
Arguments
  #self#::Core.Const(collect)
  III::InvertedIndices.InvertedIndexIterator{Int64, Int64, Base.OneTo{Int64}}
Body::Vector
1 ─ %1 = Base.Generator(Base.identity, III)::Base.Generator{InvertedIndices.InvertedIndexIterator{Int64, Int64, Base.OneTo{Int64}}, typeof(identity)}
│   %2 = Base.collect(%1)::Vector
└──      return %2
```

**Comment by mbauman** [comment]
OK, the remaining trouble with collect is that the iteration state is still marginally unstable — it's small-union-splittable unstable — but that's a union nonetheless.  At first order, this works great.  But when it's composed with other iterators (like the Generator in collect), that unstable state ends up getting stashed into a tuple where it's no longer splittable — just like the original problem.

**Comment by mbauman** [comment]
There we go, this now fixes #14, too.  It's worth noting that I tried changing iteration to use `Iterators.Stateful` in https://github.com/JuliaData/InvertedIndices.jl/compare/mbauman:InvertedIndices.jl:mb/perf...mbauman:InvertedIndices.jl:mb/stateful, but that regressed some of the above performance metrics and didn't even resolve the performance of #14 even though it fixed the type instability.  So instead, I just pushed a simple `collect` optimization here.

```
julia> @btime thing1(mean, $x);
  6.495 ms (2001 allocations: 31.02 MiB)

julia> @btime thing2(mean, $x);
  10.911 ms (4001 allocations: 62.03 MiB)
```

File: src/InvertedIndices.jl [hunk 1]
```diff
@@ -101,17 +101,49 @@ end
...
+    skipitr = iterate(I.skips)
+    pickitr = iterate(I.picks)
+    pickitr === nothing && return nothing
+    while should_skip(skipitr, pickitr)
+        skipitr = iterate(I.skips, skipitr[2])
+        pickitr = iterate(I.picks, pickitr[2])
+        pickitr === nothing && return nothing
+    end
+    # This is a little silly, but splitting the tuple here allows inference to normalize
+    # Tuple{Union{Nothing, Tuple}, Tuple} to Union{Tuple{Nothing, Tuple}, Tuple{Tuple, Tuple}}
```
Comment (ararslan) [inline src/InvertedIndices.jl:114]: Out of curiosity, have you noticed this across all supported versions or just in e.g. 1.11?

Comment (mbauman) [reply src/InvertedIndices.jl:114]: The type stability unit tests fail without this manual union-split ternary, but pass with it.  It's the difference between putting a type-unstable value in a tuple v.s. returning two different tuples... and those fundamentals hold true going back to 1.0:

```
▶ julia +1.0 -q
julia> function f()
           x = rand([nothing, 1.0])
           return (x,)
       end
f (generic function with 1 method)

julia> @code_warntype f()
Body::Tuple{Union{Nothing, Float64}}
# ...

julia> function g()
           x = rand([nothing, 1.0])
           return x===nothing ? (nothing,) : (x,)
       end
g (generic function with 1 method)

julia> @code_warntype g()
Body::Union{Tuple{Nothing}, Tuple{Float64}}
```

Comment (ararslan) [reply src/InvertedIndices.jl:114]: Oh interesting, I don't think I knew that. Thanks, I appreciate the explanation!

**Comment by ararslan** [comment]
Want to rebase for a clean CI run now that #40 has been merged?

File: test/runtests.jl [hunk 2]
```diff
@@ -185,3 +185,19 @@ end
...
+returns(val) = _->val
+@testset "type stability" begin
+    for arr in (
+            1:5,
+            reshape(1:5*3, 5, 3),
+            reshape(1:5*3*7, 5, 3, 7),
+            reshape(1:5*3*7*11, 5, 3, 7, 11),
+        )
+        I = to_indices(arr, (Not(iseven.(arr)),))[1]
+        @test all(isodd, I)
```
Comment (mbauman) [inline test/runtests.jl]:
```suggestion
        @test all(isodd, arr[I])
        @test all(isodd, LinearIndices(arr)[I])
        @test all(isodd, LinearIndices(arr)[collect(I)])
```

File: test/runtests.jl [hunk 3]
```diff
@@ -185,3 +185,21 @@ end
...
+            reshape(1:5*3*7, 5, 3, 7),
+            reshape(1:5*3*7*11, 5, 3, 7, 11),
+        )
+        I = to_indices(arr, (Not(iseven.(arr)),))[1]
+        @test all(isodd, arr[I])
+        @test all(isodd, LinearIndices(arr)[I])
+        @test all(isodd, LinearIndices(arr)[collect(I)])
+        @allocated(foreach(returns(nothing), I))
+        @test @allocated(foreach(returns(nothing), I)) == 0
+        @test @inferred(collect(I)) == vec(filter(!iseven, arr))
```
Comment (mbauman) [inline test/runtests.jl]:
```suggestion
        @test @inferred(LinearIndices(arr)[collect(I)]) == vec(filter(!iseven, arr))
```

**Review by ararslan — APPROVED** [review]
